name: Publish Extension to Azure DevOps Marketplace

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build extension
        run: npm run build

      - name: Publish to Azure DevOps Marketplace
        run: |
          echo "//registry.npmjs.org/:_authToken=\${{ secrets.AZURE_DEVOPS_PAT }}" > ~/.npmrc
          npm install -g tfx-cli
          tfx extension publish --root . --manifest-globs vss-extension.json
